<?php

namespace BlogBundle\Repository;

/**
 * empleadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class empleadorRepository extends \Doctrine\ORM\EntityRepository
{
}
