<?php

namespace BlogBundle\Repository;

/**
 * empleadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class empleadosRepository extends \Doctrine\ORM\EntityRepository
{
}
