empleador_index:
    path:     /
    defaults: { _controller: "BlogBundle:empleador:index" }
    methods:  GET

empleador_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:empleador:show" }
    methods:  GET

empleador_new:
    path:     /new
    defaults: { _controller: "BlogBundle:empleador:new" }
    methods:  [GET, POST]

empleador_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:empleador:edit" }
    methods:  [GET, POST]

empleador_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:empleador:delete" }
    methods:  DELETE
